name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.email "maximdeclient@gmail.com"
          git config --global user.name "Maxim"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./frontend 
        run: npm install

      - name: Build
        working-directory: ./frontend 
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        working-directory: ./frontend 
        run: gh-pages -d dist --repo=https://github.com/ToiletDevelopment/Skin-Overlay.git:secrets.GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
